FROM python:3.11-slim

WORKDIR /app

## Installing system dependancies
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

## Copying ur all contents from local to app
COPY . .

RUN pip install -e .

EXPOSE 8501

RUN rm Dockerfile.backend && rm -rf /backend
# Run the app 
CMD ["streamlit", "run", "frontend/app/home.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.headless=true"]